eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://3.34.127.65:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://j10c206.p.ssafy.io:3306/prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true

swagger:
  server: https://giveus.site

notification:
  auth-url: https://backend-auth/api/v1/auth/device