spring:
  application:
    name: backend-payment
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    hikari:
      connection-test-query: select 1
      username: giveus
      password: giveus2024~!
  data:
    redis:
      host: j10c206.p.ssafy.io
      port: 6379
      password: giveus2024~!
      repositories:
        enabled: false

server:
  port: 8084
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

management:
  health:
    refresh:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    operations-sorter: alpha
    path: /docs
  api-docs:
    path: /api/v1/payment/docs
  packages-to-scan: com.giveus.payment.controller

pay:
  kakao:
    cid: TC0ONETIME
    secret-key: DEV8BED019BC61B73FE2595FB95EC2E08D8A824D
  toss:
    secret-key: test_sk_yL0qZ4G1VOdvqNwkoXKoroWb2MQY