export const columnsData = [
  {
    accessor: 'fundingNo',
    Header: '번호',
  },
  {
    accessor: 'registrationNumber',
    Header: '환자번호',
  },
  {
    accessor: 'patientName',
    Header: '환자성명',
  },
  {
    accessor: 'birth',
    Header: '생년월일',
  },
  {
    accessor: 'diseaseName',
    Header: '병명',
  },
  {
    accessor: 'status',
    Header: '펀딩상태',
  },
  {
    accessor: 'targetAmount',
    Header: '목표금액',
  },
]

export const dummyData = [
  {
    fundingNo: 1,
    registrationNumber: 'REG001',
    patientName: '홍길동',
    birth: '1950-01-01',
    disease_name: '간암',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 2,
    registrationNumber: 'REG002',
    patientName: '김싸피',
    birth: '1960-01-01',
    disease_name: '배탈',
    status: '진행중',
    target_amount: 100000,
  },
  {
    fundingNo: 3,
    registrationNumber: 'REG003',
    patientName: '아무개',
    birth: '1999-01-01',
    disease_name: '백혈병',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 4,
    registrationNumber: 'REG004',
    patientName: '도적',
    birth: '1970-01-01',
    disease_name: '폐암',
    status: '진행중',
    target_amount: 30000000,
  },
  {
    fundingNo: 5,
    registrationNumber: 'REG005',
    patientName: '김가가',
    birth: '1956-01-01',
    disease_name: '뇌졸중',
    status: '진행중',
    target_amount: 50000000,
  },
  {
    fundingNo: 6,
    registrationNumber: 'REG006',
    patientName: '이무기',
    birth: '1980-01-01',
    disease_name: '맹장',
    status: '진행중',
    target_amount: 1000000,
  },
  {
    fundingNo: 7,
    registrationNumber: 'REG007',
    patientName: '홍두깨',
    birth: '1980-01-01',
    disease_name: '장염',
    status: '진행중',
    target_amount: 2000000,
  },
  {
    fundingNo: 1,
    registrationNumber: 'REG001',
    patientName: '홍길동',
    birth: '1950-01-01',
    disease_name: '간암',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 2,
    registrationNumber: 'REG002',
    patientName: '김싸피',
    birth: '1960-01-01',
    disease_name: '배탈',
    status: '진행중',
    target_amount: 100000,
  },
  {
    fundingNo: 3,
    registrationNumber: 'REG003',
    patientName: '아무개',
    birth: '1999-01-01',
    disease_name: '백혈병',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 4,
    registrationNumber: 'REG004',
    patientName: '도적',
    birth: '1970-01-01',
    disease_name: '폐암',
    status: '진행중',
    target_amount: 30000000,
  },
  {
    fundingNo: 5,
    registrationNumber: 'REG005',
    patientName: '김가가',
    birth: '1956-01-01',
    disease_name: '뇌졸중',
    status: '진행중',
    target_amount: 50000000,
  },
  {
    fundingNo: 6,
    registrationNumber: 'REG006',
    patientName: '이무기',
    birth: '1980-01-01',
    disease_name: '맹장',
    status: '진행중',
    target_amount: 1000000,
  },
  {
    fundingNo: 7,
    registrationNumber: 'REG007',
    patientName: '홍두깨',
    birth: '1980-01-01',
    disease_name: '장염',
    status: '진행중',
    target_amount: 2000000,
  },
  {
    fundingNo: 1,
    registrationNumber: 'REG001',
    patientName: '홍길동',
    birth: '1950-01-01',
    disease_name: '간암',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 2,
    registrationNumber: 'REG002',
    patientName: '김싸피',
    birth: '1960-01-01',
    disease_name: '배탈',
    status: '진행중',
    target_amount: 100000,
  },
  {
    fundingNo: 3,
    registrationNumber: 'REG003',
    patientName: '아무개',
    birth: '1999-01-01',
    disease_name: '백혈병',
    status: '진행중',
    target_amount: 10000000,
  },
  {
    fundingNo: 4,
    registrationNumber: 'REG004',
    patientName: '도적',
    birth: '1970-01-01',
    disease_name: '폐암',
    status: '진행중',
    target_amount: 30000000,
  },
  {
    fundingNo: 5,
    registrationNumber: 'REG005',
    patientName: '김가가',
    birth: '1956-01-01',
    disease_name: '뇌졸중',
    status: '진행중',
    target_amount: 50000000,
  },
  {
    fundingNo: 6,
    registrationNumber: 'REG006',
    patientName: '이무기',
    birth: '1980-01-01',
    disease_name: '맹장',
    status: '진행중',
    target_amount: 1000000,
  },
  {
    fundingNo: 7,
    registrationNumber: 'REG007',
    patientName: '홍두깨',
    birth: '1980-01-01',
    disease_name: '장염',
    status: '진행중',
    target_amount: 2000000,
  },
]
